[tool.poetry]
name = "base-project"
version = "0.1.0"
description = ""
authors = ["Dongjin Yoon <djyoon0223@gmail.com>"]
readme = "README.md"
packages = [{include = "base_project"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.3"
pyyaml = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
